</main>

<footer class="flex" style="justify-content:space-between;align-items:center;padding:1rem">
  <div>
    <h4>Contact Us</h4>
    <a href="tel:509-449-8989">509-449-8989</a><br>
    PO Box 64<br>
    Manson, WA. 98831<br>
    <a href="mailto:chris@aghawkdynamics.com">chris@aghawkdynamics.com</a><br>

  </div>

  <div class="right flex" style="gap:.6rem;align-items:center">
    <div>
      <span style="">AG</span><span>HAWK</span>
      <br> 
      DYNAMICS
    </div>
    <a href="https://www.facebook.com/profile.php?id=61566182047013" target="_blank"><img src="/public/img/social/ftrSocialFB.png" alt="Facebook" width="24" height="24"></a>
    <a href="https://www.instagram.com/aghawk.dynamics/" target="_blank"><img src="/public/img/social/ftrSocialIG.png" alt="Instagram" width="24" height="24"></a>
    <a href="https://www.youtube.com/@Aghawk.Dynamics" target="_blank"><img src="/public/img/social/ftrSocialYT.png" alt="YouTube" width="24" height="24"></a>
    <a href="https://www.x.com/AghawkDynamics" target="_blank"><img src="/public/img/social/ftrSocialX.png" alt="X (Twitter)" width="24" height="24"></a>
    <a href="https://www.tiktok.com/@aghawkdynamics" target="_blank"><img src="/public/img/social/ftrSocialTT.png" alt="TikTok" width="24" height="24"></a>
  </div>
</footer>
</body>

</html>